on: [pull_request]
name: Pull Request Feedback

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Run linter
        run: |
          echo TODO: Implement linting
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Run tests
        run: |
          RELEASE="feedback build for $GITHUB_SHA" tools/release-update.sh
          go test ./...
  build:
    name: Build Feedback Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build image
        run: |
          RELEASE="feedback build for $GITHUB_SHA" tools/release-update.sh
          DOCKER_TAG=$GITHUB_SHA
          docker build . -t tsal/ataxia-go:$DOCKER_TAG
          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_USER }}/ataxia-go:$DOCKER_TAG
          echo "Published ataxia-go:$DOCKER_TAG"
  integration:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests
        run: |
          echo TODO: Implement integration testing
