on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: Upload Release Asset

jobs:
  release:
    name: Build Release for all supported platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Release deps
        run: |
          rm -rf go.sum
          go mod download && go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes=CHANGES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get Info
        id: release_info
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MINOR=${TAG%.*}
          MAJOR=${MINOR%.*}
          echo ::set-output name=tag_name::${TAG}
          echo ::set-output name=minor_tag::${MINOR}
          echo ::set-output name=major_tag::${MAJOR}
          echo ::set-output name=major_exists::$(git show-ref origin/releases/${MAJOR})
      - name: Build Image
        run: |
          tools/release-update.sh
          docker build . -t tsal/ataxia-go:latest
          docker tag ${{ secrets.DOCKER_USER }}/ataxia-go:latest ${{ secrets.DOCKER_USER }}/ataxia-go:${{ steps.release_info.outputs.tag_name }}
          docker tag ${{ secrets.DOCKER_USER }}/ataxia-go:latest ${{ secrets.DOCKER_USER }}/ataxia-go:${{ steps.release_info.outputs.major_tag }}-latest
          docker tag ${{ secrets.DOCKER_USER }}/ataxia-go:latest ${{ secrets.DOCKER_USER }}/ataxia-go:${{ steps.release_info.outputs.minor_tag }}-latest
          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_USER }}/ataxia-go:latest
          docker push ${{ secrets.DOCKER_USER }}/ataxia-go:${{ steps.release_info.outputs.tag_name }}
          docker push ${{ secrets.DOCKER_USER }}/ataxia-go:${{ steps.release_info.outputs.major_tag }}-latest
          docker push ${{ secrets.DOCKER_USER }}/ataxia-go:${{ steps.release_info.outputs.minor_tag }}-latest
