on:
  push:
    brnaches:
      - 'master'

name: Upload Release Asset

jobs:
  release:
    name: Release for all platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Release deps
        run: |
          rm -rf go.sum
          go mod download && go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
